"""Refactor models renomeacao tabelas e colunas

Revision ID: 49714474b532
Revises: db3549fcd006
Create Date: 2025-12-14 18:38:19.249167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49714474b532'
down_revision: Union[str, Sequence[str], None] = 'db3549fcd006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carteiraestudantil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validade', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status_carteira', sa.Boolean(), nullable=False),
    sa.Column('numero_de_registro', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_de_registro')
    )
    op.drop_table('carteira_estudantil')
    op.add_column('disciplina', sa.Column('departamento_disciplina_cod', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('disciplina', 'id_professor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('disciplina_departamento_disciplina_fkey'), 'disciplina', type_='foreignkey')
    op.create_foreign_key(None, 'disciplina', 'departamento', ['departamento_disciplina_cod'], ['codigo_departamento'])
    op.drop_column('disciplina', 'departamento_disciplina')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplina', sa.Column('departamento_disciplina', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'disciplina', type_='foreignkey')
    op.create_foreign_key(op.f('disciplina_departamento_disciplina_fkey'), 'disciplina', 'departamento', ['departamento_disciplina'], ['codigo_departamento'])
    op.alter_column('disciplina', 'id_professor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('disciplina', 'departamento_disciplina_cod')
    op.create_table('carteira_estudantil',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('validade', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id_aluno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status_carteira', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('numero_de_registro', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], name=op.f('carteira_estudantil_id_aluno_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carteira_estudantil_pkey')),
    sa.UniqueConstraint('numero_de_registro', name=op.f('carteira_estudantil_numero_de_registro_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('carteiraestudantil')
    # ### end Alembic commands ###
