"""primeira criação das tabelas

Revision ID: db3549fcd006
Revises: 
Create Date: 2025-12-13 11:15:13.593537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db3549fcd006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('numero_matricula', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_departamento', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamento_codigo_departamento'), 'departamento', ['codigo_departamento'], unique=True)
    op.create_index(op.f('ix_departamento_nome'), 'departamento', ['nome'], unique=True)
    op.create_table('carteira_estudantil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validade', sa.DateTime(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status_carteira', sa.Boolean(), nullable=False),
    sa.Column('numero_de_registro', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_de_registro')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('departamento_disciplina', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_disciplina'], ['departamento.codigo_departamento'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matricula',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=True),
    sa.Column('numero_faltas', sa.Integer(), nullable=False),
    sa.Column('semestre', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id_aluno', 'disciplina_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matricula')
    op.drop_table('disciplina')
    op.drop_table('professor')
    op.drop_table('carteira_estudantil')
    op.drop_index(op.f('ix_departamento_nome'), table_name='departamento')
    op.drop_index(op.f('ix_departamento_codigo_departamento'), table_name='departamento')
    op.drop_table('departamento')
    op.drop_table('aluno')
    # ### end Alembic commands ###
